apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-qs-dev
spec:
  template:
    spec:
      containers:
      - image: "us-west1-docker.pkg.dev/clouddeploy-1-375023/cd-cr-noodling/my-app-image:latest"
