apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: my-run-demo-app-1
description: main application pipeline
serialPipeline:
 stages:
 - targetId: run-qsdev
   profiles: [dev]
 - targetId: run-qsstaging
   profiles: [staging]
 - targetId: run-qsprod
   profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: run-qsdev
description: Cloud Run development service
run:
 location: projects/clouddeploy-1-dev/locations/us-west1
# executionConfigs:
# - usages:
#   - DEPLOY
#   - VERIFY
#   - RENDER
#   serviceAccount: manual-deploy-sa@clouddeploy-1-375023.iam.gserviceaccount.com
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: run-qsstaging
description: Cloud Run staging service
run:
 location: projects/clouddeploy-1-staging/locations/us-west1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: run-qsprod
description: Cloud Run production service
run:
 location: projects/clouddeploy-1-prod/locations/us-west1
